name = "ts-kv-tester"
type = "javascript"
zone_id = ""
account_id = ""
route = ""
workers_dev = true
compatibility_date = "2021-11-10"
kv_namespaces = [ 
  { binding = "SHEARICHARD_TEST_0", id = "979e3d873f9d4fa4ab6c251dad403c30" }
]

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"
