export async function handleRequest(request: Request): Promise<Response> {
    let datetime: Date = new Date(2019,0o4,27,18,0o1,30,15); 
    const html : string = `<!DOCTYPE html>
          <body>
            <h1>Hello World</h1>
            <p>This markup was generated by a Cloudflare Worker.</p>
            <p>The request method was : ${request.method}.</p><p>The date/time was ${datetime}</p>
          </body>
        `;
    return new Response(html, {
        headers: {
            "content-type": "text/html;charset=UTF-8",
        },
    });
}
